### PR TITLE
Bump to 3.0.2

### PR DESCRIPTION
**Pull request by Zlopez**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by Zlopez** [comment]
I tried to test it on my machine, but unfortunately I'm hitting https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/20

**Comment by tilosp** [comment]
3.0.2 is now available in the beta repo.

@Zlopez are you also hitting #20 on 3.0.1?

**Comment by Zlopez** [comment]
@tilosp Yes, this is why I created this PR

**Comment by Zlopez** [comment]
I would love to try downgrading the KDE runtime to 5.14 and see if this helps with #20

**Comment by Zlopez** [comment]
Downgrade didn't help with #20 :-(

**Pull request closed without merging**
