### PR TITLE
restore talking to kde wallet, fix #125

### LINKED ISSUE #125: Nextcloud Desktop no longer have access to KDE wallet
Since latest changes in the repo, the app cannot use KDE wallet, and is asking for authorization via web browser each time it starts.

### PR DESCRIPTION
**Pull request by Szwendacz99**
The app lost ability to use KDE wallet, possibly after removing `- --own-name=org.kde.*` in ([#112](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/112)). This change might restore it.

Edit: this fixes #125

### CODE REVIEW

**Comment by Szwendacz99** [comment]
For me it seem to fix the issue with KDE wallet integration - app no longer ask to log in via web browser on app start/restart.

**Comment by bram-pkg** [comment]
Seems to work for me too.

**Comment by Justinzobel** [comment]
If this fixes the issue, can we get it merged, please?

**Comment by bram-pkg** [comment]
This is a temporary fix: https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/125#issuecomment-1765303577

**Comment by tilosp** [comment]
Thanks for your contribution!

**Comment by Croydon** [comment]
Thank you!

**Pull request merged**
